### ISSUE TITLE
Mobiil-ID, Smart ID support

### ISSUE THREAD

**Issue by notpushkin** [web-eid/web-eid-app#188]
Is it possible at all? What would it take to implement it?

**Comment by karl80038** [comment]
Web-eID is a solution that enables the use of eID-Cards (such as the Estonian ID-Card) for authentication and signing purposes over the web. The Mobiil-ID and Smart-ID solutions differ from it and are also mainta
Ined by different vendor(s). Implementing supporting code to the Web-eID Server API(s) could likely result in a more complex solution that would be more difficult and more time consuming to maintain. But who knows, I don't work at nor for RIA, so I've no idea what happens over there.

**Comment by kristelmerilain** [comment]
Thank you for the proposal.
Currently there are no plans to add mobile-ID and Smart-ID support to Web eID.
