### ISSUE TITLE
MacOS build failing, some NSWorkspace components deprecated

### ISSUE THREAD

**Issue by Muzosh** [web-eid/web-eid-app#204]
My build attempts keep failing with deprecation messages:
<img width="1297" alt="image" src="https://user-images.githubusercontent.com/30979983/173325948-de9f02d7-f632-40c9-a456-b73e31d3f959.png">
<img width="1291" alt="image" src="https://user-images.githubusercontent.com/30979983/173326108-9bb9cbac-b20a-49a2-b768-a4f6b4b77fc2.png">

My last successful build was on 10.05.2022, but when I look at file history of `application.mm`, I don't see any recent changes.

Relevant versions:
**Repo:** latest main (https://github.com/web-eid/web-eid-app/commit/437adeadf69a88a08c7787077f494be06155f39b)
**Build tools:** xcode-select version 2395
**Clang:** Clang 13.1.6 arm64-apple-darwin21.5.0
**MacOS:** 12.4

Could this be somehow related to this repository or is there something wrong with my configuration?

**Comment by mrts** [comment]
I did update the README in #207.
