### ISSUE TITLE
webextension cannot communicate with native app (`ERR_WEBEID_NATIVE_UNAVAILABLE`) in Fedora

### ISSUE THREAD

**Issue by mrtnschltr** [web-eid/web-eid-app#219]
Hi guys!

thx for the great work you're doing here!

I'm trying to get the stack running on a Fedora 36 system.
I've successfully compiled and installed the `web-eid-app` following the instructions given in https://github.com/web-eid/web-eid-app/pull/173 (https://github.com/web-eid/web-eid-app/pull/173#issuecomment-1018874023)

Running the python tests as stated in the [`input-output mode`-section in the README](https://github.com/web-eid/web-eid-app#input-output-mode) also succeeds.

However, communication to the native app via the browser extensions fails. I'm using https://web-eid.eu/ to test the flow. This is the error I'm shown:
![image](https://user-images.githubusercontent.com/1927667/189330642-22883737-e146-4abf-a39a-5c22f13bb113.png)

If that helps in any way, this is the line that throws:
![image](https://user-images.githubusercontent.com/1927667/189330979-dbbbb874-d917-4833-b1db-d3b0718fffa9.png)

@eidins maybe you can bring some light to this?

**Comment by mrtnschltr** [comment]
Hi @mrts,
thx for your help!

It's working now. [eu.webeid.json](https://github.com/web-eid/web-eid-app/blob/main/install/eu.webeid.firefox.json.cmake) was indeed the file causing trouble. It was and is present in one of the paths mentioned in [MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_manifests#linux) (`/usr/lib64/mozilla/native-messaging-hosts/eu.webeid.json`)

I didn't have to set any symlinks but the `path` key held a false value: `/usr/local/bin/web-eid` while a call to `which web-eid` revealed the binary sitting in `/usr/bin/web-eid`. Correcting that value solved the issue.

I'd contribute a fix but unfortunately it's not clear to me how to exactly this needs to be fixed (not really familiar with cmake). It seems like [`CMAKE_INSTALL_FULL_BINDIR`](https://github.com/web-eid/web-eid-app/blob/fb09a7f0416237fd147586226c8143ab3ef9c48f/src/app/CMakeLists.txt#L168) is not holding the correct value in my case.

**Comment by mrts** [comment]
@mrtnschltr, thank you! This will however unfortunately break Ubuntu.

There is another way by specifying `-DCMAKE_INSTALL_PREFIX=/usr` during build. Can you please if https://github.com/web-eid/web-eid-app/pull/223/files works?

**Comment by mrtnschltr** [comment]
Yes that does the trick!

**Comment by mrts** [comment]
Thank you for testing!
