### ISSUE TITLE
Q: is Web eID extension still required

### ISSUE THREAD

**Issue by laur89** [web-eid/web-eid-app#243]
Installed the eID package using the [linux installer](https://github.com/open-eid/linux-installer) script, which installs the `PKCS11 loader` firefox extension (`firefox-pkcs11-loader` pkg).

Testing auth on https://test-eid.eesti.ee/auth/ page succeeds - PIN1 is asked and accepted.

Question is, what is [Web eID](https://addons.mozilla.org/en-US/firefox/addon/web-eid-webextension/) extension for, and is it still needed? Note I don't have it installed, yet the abovementioned test succeeds.

**Comment by kristelmerilain** [comment]
PKCS11 loader is used for authentication when website uses TLS-CCA solution.
Web eID extension is used for authentication (if website is uses Web eID solution) and signing.
You can find more information about it from here - https://www.id.ee/en/article/web-eid/#backward-compatibility
