### ISSUE TITLE
Sandboxed/non-sandboxed logging on MacOS is insufficiently documented

### ISSUE THREAD

**Issue by Muzosh** [web-eid/web-eid-app#253]
It seems that correct `plist` location to enable logging into file for Web eID app is `~/Library/Preferences/eu.web-eid.web-eid.plist` (expecting key-value "logging":"true"). Logs are then available in `~/Library/Application Support/RIA/web-eid/web-eid.log`.

I discovered both of these locations by debugging controller/logging.cpp. Is this related only to my workstation? In README.md, both locations are different and do not work for me.

**Comment by mrts** [comment]
Well, it is tricky. The Web eID extension runs in a sandbox in macOS, so the locations in the README are actually correct for the sandboxed case. 

However, you run it from the command line, so your point is also valid. Can you come up with a good explanation in the README?

**Comment by Muzosh** [comment]
Yes it makes sense, thank you! Didn't realize the sandbox stuff.

**Comment by Muzosh** [comment]
Apologies if I am bothering with unimportant stuff. Writing a quick issue seems to me like a good place to do that since everyone can decide how important the issue is.

**Comment by mrts** [comment]
No problem at all, it is a valuable and valid problem report - thanks for submitting it! It may be low priority, but it is still good to have it.
