### ISSUE TITLE
Web eID Qt UI does not work on NixOS

### ISSUE THREAD

**Issue by P-E-Meunier** [web-eid/web-eid-app#256]
The example given in the readme yields the following output:

```
INFO: "web-eid" app "2.3.1+0" running in command-line mode
DEBUG: Starting "WaitForCardThread" 140041569504272 for command "INSERT_CARD"
INFO: "WaitForCardThread" 140041569504272 for command "INSERT_CARD" completed successfully
INFO: Card "EstEID IDEMIA v1" in reader "ACS ACR38U-CCID 00 00" using protocol T=1
DEBUG: Thread 140041569504272 finished
DEBUG: "WaitForCardThread" 140041569504272 destroyed
DEBUG: Starting "CommandHandlerRunThread" 39819104 for command "SIGN"
INFO: "CommandHandlerRunThread" 39819104 for command "SIGN" completed successfully
DEBUG: Thread 39819104 finished
DEBUG: "CommandHandlerRunThread" 39819104 destroyed
```

And stops. While this is printing, there's a window trying to exist but it actually just blinks.

The platform is Linux, but not "Ubuntu" (which isn't a platform anyway).

**Comment by P-E-Meunier** [comment]
Exactly that example.

> Which Linux distribution and version it is? We officially support only Ubuntu precisely because of problems like this.

Right, but I won't change my Linux distribution just for this package. I have no idea what the problem is, I tried to debug, and I'm now rewriting a frontend to libelectronid-id without using Qt (which is a portability nightmare), I'll keep you posted.

The distribution is NixOS.

**Comment by mrts** [comment]
Thanks, please keep us posted. We chose Qt because of portability across platforms (not distributions) and beacuse of the highly dynamic nature of the UI.

**Comment by antirais** [comment]
I've noticed same issue on linux host. Fix for this was to revert latest patch - see PR #262.

**Comment by mrts** [comment]
@P-E-Meunier, we just merged #264 that may fix this. Can you please try latest main and see if it is fixed?

**Comment by Silur** [comment]
still happening on arch linux too

**Comment by antirais** [comment]
I build and test this patch on arch also. Worked for me.

**Comment by mrts** [comment]
@antirais https://github.com/web-eid/web-eid-app/pull/264/files is identical to your patch. Does current master work for you on Arch without your patch?

**Comment by antirais** [comment]
> Does current master work for you on Arch without your patch?

Tested on current main (#d070827) and it built cleanly and works fine as is.
