### ISSUE TITLE
Windows build instructions

### ISSUE THREAD

**Issue by fabiojuniorr** [web-eid/web-eid-app#283]
Hi,

I'm getting some errors when I try to run the build install command, the build and tests run successfully but when I run the command below to install I get the following error:

Installed some dependencies:
cmake - 3.27.0
openssl - 1.1.1
GTest - 1.13.0
VS - 2019
Qt - 6.2.4
and other stuff...

**cmake --build build --config RelWithDebInfo --target installer**
```
Microsoft(R) Build Engine versão 16.11.2+f32259642 para .NET Framework
Copyright (C) Microsoft Corporation. Todos os direitos reservados.

  pcsc-cpp.vcxproj -> C:\desenvolvimento\projetos\others\web-eid\web-eid-app\build\lib\libelectronic-id\lib\libpcsc-cpp\RelWithDebInfo\pcsc-cpp.lib
  electronic-id.vcxproj -> C:\desenvolvimento\projetos\others\web-eid\web-eid-app\build\lib\libelectronic-id\RelWithDebInfo\electronic-id.lib
  Automatic MOC for target controller
  controller.vcxproj -> C:\desenvolvimento\projetos\others\web-eid\web-eid-app\build\src\controller\RelWithDebInfo\controller.lib
  Automatic MOC and UIC for target ui
  ui.vcxproj -> C:\desenvolvimento\projetos\others\web-eid\web-eid-app\build\src\ui\RelWithDebInfo\ui.lib
  Automatic MOC for target web-eid
  web-eid.vcxproj -> C:\desenvolvimento\projetos\others\web-eid\web-eid-app\build\src\app\RelWithDebInfo\web-eid.exe
 The system cannot find the path specified.
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB8066: the custom build for 'C:\desenvolvimento\projetos\others\web-eid\web-eid-app\build\CMakeFiles\f4fae8a8d0ee107223a962feaa24a736\installer.rule;C:\desenvolvimento\projetos\o
thers\web-eid\web-eid-app\src\app\CMakeLists.txt' terminated with code 3. [C:\desenvolvimento\projetos\others\web-eid\web-eid-app\build\src\app\installer.vcxproj]
```

About the message `The system cannot find the path specified`, I already verify the file `build\src\app\RelWithDebInfo\web-eid.exe `and de same was created in the directory.

I noticed that the file **installer.rule** was generated empty, is that right?

Thanks.

**Comment by mrts** [comment]
Hi Fabio!

I'm not sure what exactly causes the error, but as we know for certain that Windows builds work in GitHub, I would recommend that you check out the build job definition [here](https://github.com/web-eid/web-eid-app/blob/main/.github/workflows/cmake-windows.yml) and try to carefully replicate it step-by-step.

Does that solve your problem?
