### ISSUE TITLE
Using istead of third-party signing programs

### ISSUE THREAD

**Issue by tmarkov** [web-eid/web-eid-app#299]
Some websites implement signing documents using third party tools such as `NexU` or `BISS`. For example, [these instructions](https://ec.europa.eu/digital-building-blocks/wikis/display/ESIGKB/How+can+I+sign+a+document+via+the+Sign+a+document+webpage) require that `NexU` be installed.

Can I use `web-eid` for signing on these pages instead? If so where can I look which are supported, and how to potentially add support for others.

**Comment by mrts** [comment]
It is not likely. The pages have to add support for Web eID and use it in the back-end as well.

For your reference, instructions how to add Web eID support to a Java web application back-end are [here](https://github.com/web-eid/web-eid-authtoken-validation-java#quickstart) and to the corresponding front-end [here](https://github.com/web-eid/web-eid.js#quickstart). We also provide official support for .NET and PHP applications.
