### ISSUE TITLE
`web-eid-app` for NixOS: pin1 works, pin2 don't

### ISSUE THREAD

**Issue by getreu** [web-eid/web-eid-app#317]
NixOS comes with the package [web-eid-app](https://search.nixos.org/packages?channel=23.11&from=0&size=50&sort=relevance&type=packages&query=web-eid) and [instructions for Estonians](https://nixos.wiki/wiki/Web_eID#PKCS.2311) .

With Firefox and the above config for NixOS 23.11, I can authenticate with e.g. <https://lhv.ee> but I can not sign. Any ideas?

I know, you do not officially support NixOS, but maybe some of you uses it and can help. Here my config:

```nix
services.pcscd.enable = true;
programs.firefox.enable = true;
programs.firefox.nativeMessagingHosts.packages = [ pkgs.web-eid-app ];
programs.firefox.policies.SecurityDevices.p11-kit-proxy = "${pkgs.p11-kit}/lib/p11-kit-proxy.so";
environment.etc."chromium/native-messaging-hosts/eu.webeid.json".source = "${pkgs.web-eid-app}/share/web-eid/eu.webeid.json";
environment.etc."opt/chrome/native-messaging-hosts/eu.webeid.json".source = "${pkgs.web-eid-app}/share/web-eid/eu.webeid.json";
environment.etc."pkcs11/modules/opensc-pkcs11".text = ''
  module: ${pkgs.opensc}/lib/opensc-pkcs11.so
'';
```

**Comment by getreu** [comment]
Is this related to #309 ?

**Comment by mrts** [comment]
What error do you see?
Can you please turn on native app logging as described here: https://web-eid.eu/ > _Debugging and logs_ and check the log?

**Comment by getreu** [comment]
When I press [Authenticate] on  <https://web-eid.eu/> I get (in pink color):

```
Authentication failed

[Code]
ERR_WEBEID_EXTENSION_UNAVAILABLE

[Message]
Web-eID extension is not available
```

Strangely I can authenticate with <https://lhv.ee>.
After login in into the bank, there is still no log file:

In `~/.local/share/RIA/` is no `web-eid.log`.

When I start the binary from the console, I get:

```
$ web-eid 
INFO: "web-eid" app "2.4.0+0" running in command-line mode
```

Now the log file is created with the contents:

```
024-03-25T13:11:44.212Z INFO src/controller/controller.cpp:72:void Controller::run() - "web-eid" app "2.4.0+0" running in command-line mode
```

Is `web-eid` known to the firefox browser?

**Comment by mrts** [comment]
It looks like the extension is not installed in Firefox. Here's how it should look:

![image](https://github.com/web-eid/web-eid-app/assets/44880/8045764d-a2f3-4b99-bd0d-99a20dea9a05)

You can add the extension manually from here:
https://addons.mozilla.org/en-US/firefox/addon/web-eid-webextension/

**Comment by getreu** [comment]
It seem it is a NixOS firefox package related problem. I do not manage enable the extension. It does not even show in the browser tab (cf. your screenshot) above. If I get it work, I leave a note here. Thank you so far.

**Comment by getreu** [comment]
![Screenshot_2024-03-27_15-39-39](https://github.com/web-eid/web-eid-app/assets/579082/fd000cab-b725-4876-be90-3950e9d51f7e)
![Screenshot_2024-03-27_15-35-38](https://github.com/web-eid/web-eid-app/assets/579082/aa71462f-ed51-41a6-bba0-d048956d4f7a)

No log entry in `web-eid.log`, but I can start the app from the command line. 
![Screenshot_2024-03-27_15-43-38](https://github.com/web-eid/web-eid-app/assets/579082/ba0f46bc-65f9-4d6e-abca-8dd2e43416f1)

**Comment by sergey-abc** [comment]
@getreu just in case  check "Security Devices" section of Firefox settings. 
![image](https://github.com/web-eid/web-eid-app/assets/23507546/eab56603-6ba3-43bc-af96-045883a17947)
Maybe You have to add (or unload and then load again)  "onepin-opensc-pkcs11.so", this file can be located in different folder.

**Comment by getreu** [comment]
@sergey-abc  I have this:
![Screenshot_2024-03-31_10-13-24](https://github.com/web-eid/web-eid-app/assets/579082/32860852-a38c-461e-b8af-d7bae5cb6ace)

**Comment by getreu** [comment]
Summary of my efforts. Please correct where I am wrong.

## Installation

1. Install the `web-eid-app` package in NixOS

   Insert in `configuration.nix`:

   ```nix
    packages = with pkgs; [
      firefox-esr
      web-eid-app
      p11-kit
      opensc
      
    ];
   ```

   and below:

   ```nix
   services.pcscd.enable = true;
   programs.firefox.enable = true;
   programs.firefox.package = pkgs.firefox-esr;
   programs.firefox.nativeMessagingHosts.packages = [ pkgs.web-eid-app ];
   programs.firefox.policies.SecurityDevices.p11-kit-proxy = "${pkgs.p11-kit}/lib/p11-kit-proxy.so";
   # Authentification
   environment.etc."pkcs11/modules/opensc-pkcs11".text = ''
     module: ${pkgs.opensc}/lib/opensc-pkcs11.so
   '';
   ```

2. Enable logging (for testing only)

   1. Enable logging:

      ```sh
      echo 'logging=true' > ~/.config/RIA/web-eid.conf
      ```

   2. Check success:

      ```sh
      web-eid
      ```

      A dialogue _About Web eID_ window appears. Click on `[Cancel]`.

      ```sh
      cat /.local/share/RIA/web-eid/web-eid.log
      ```

      You should see something like:

      ```
      2024-03-31T06:56:42.804Z INFO src/controller/controller.cpp:72:void Controller::run() - "web-eid" app "2.4.0+0" running in command-line mode
      ```
      

3. Install the browser extension within Firefox from
   [Web eID – Get this Extension for Firefox (en-US)](https://addons.mozilla.org/en-US/firefox/addon/web-eid-webextension/) 

4. Link the `web-eid` manifest into the browser configuration

   ```sh
   mkdir -p ~/.mozilla/native-messaging-hosts/
   cd ~/.mozilla/native-messaging-hosts/
   ln -s $(dirname $(dirname $(realpath $(which web-eid))))/share/web-eid/eu.webeid.json .

5. Check success

   1. Enable logging: 
   1. Insert Estionan ID card.
   2. Check with DigiDoc that the card reader works and the ID card reader and
      driver works. (Ok)
   3. Goto <https://web-eid.eu/> and click on `[Authenticate]`.



## Result


Unfortunately, I get the following error page in the browser:

```   
Authentication failed
[Code]
ERR_WEBEID_NATIVE_UNAVAILABLE
[Message]
a message from native application was expected, but native application closed connection
```

Furthermore, no log message in `/.local/share/RIA/web-eid/web-eid.log`.

**Comment by getreu** [comment]
I also filed an issue here: https://github.com/NixOS/nixpkgs/issues/300435

**Comment by mrts** [comment]
Great, the extension is enabled now. Please try on <https://web-eid.eu/>, Firefox is probably unable to locate the native app.

**Comment by mrts** [comment]
Thanks for your thorough investigation! The `ERR_WEBEID_NATIVE_UNAVAILABLE` message indicates that Firefox is unable to  locate the native messaging host. 

Please check that the native messaging manifest file has the following content:

```
{
"name": "eu.webeid",
"description": "Web-eid native application",
"path": "/usr/bin/web-eid",
"type": "stdio",
"allowed_extensions": [ "{e68418bc-f2b0-4459-a9ea-3e72b6751b07}" ]
}
```

Verify the value of `allowed_extensions` and that `/usr/bin/web-eid` exists.

If the content is correct, linking the file to `~/.mozilla/native-messaging-hosts/` should indeed work according to https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_manifests#linux. Can you check the symlink just in case or even copy the file in case Firefox does not follow symlinks for some reason? If you still get `ERR_WEBEID_NATIVE_UNAVAILABLE` when trying to authenticate on <web-eid.eu>, then please try the global locations listed in https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_manifests#linux, start from  `/usr/lib/mozilla/native-messaging-hosts/eu.webeid.json`.

**Comment by getreu** [comment]
@mrts
The manifest was the problem. 

In the manual above, I replaced the line:

```sh
ln -s "$(dirname $(dirname $(realpath $(which web-eid))))/share/web-eid/eu.webeid.json" .
```

with 

```sh
ls -s "$(dirname $(dirname $(realpath $(which web-eid))))/lib/mozilla/native-messaging-hosts/eu.webeid.json" .
```

I edited the above.

And authentification and signing works. Thank you a lot!

**Comment by getreu** [comment]
# Tested working procedure:

## Installation

1. Install the `web-eid-app` package in NixOS

   Insert in `configuration.nix`:

   ```nix
    packages = with pkgs; [
      firefox-esr
      web-eid-app
      p11-kit
      opensc
      
    ];
   ```

   and below:

   ```nix
   services.pcscd.enable = true;
   programs.firefox.enable = true;
   programs.firefox.package = pkgs.firefox-esr;
   programs.firefox.nativeMessagingHosts.packages = [ pkgs.web-eid-app ];
   programs.firefox.policies.SecurityDevices.p11-kit-proxy = "${pkgs.p11-kit}/lib/p11-kit-proxy.so";
   # Authentification
   environment.etc."pkcs11/modules/opensc-pkcs11".text = ''
     module: ${pkgs.opensc}/lib/opensc-pkcs11.so
   '';
   ```

2. Enable logging (for testing only)

   1. Enable logging:

      ```sh
      echo 'logging=true' > ~/.config/RIA/web-eid.conf
      ```

   2. Check success:

      ```sh
      web-eid
      ```

      A dialogue _About Web eID_ window appears. Click on `[Cancel]`.

      ```sh
      cat /.local/share/RIA/web-eid/web-eid.log
      ```

      You should see something like:

      ```
      2024-03-31T06:56:42.804Z INFO src/controller/controller.cpp:72:void Controller::run() - "web-eid" app "2.4.0+0" running in command-line mode
      ```
      

3. Install the browser extension within Firefox from
   [Web eID – Get this Extension for Firefox (en-US)](https://addons.mozilla.org/en-US/firefox/addon/web-eid-webextension/) 

4. Link the `web-eid` manifest into the browser configuration

   ```sh
   mkdir -p ~/.mozilla/native-messaging-hosts/
   cd ~/.mozilla/native-messaging-hosts/
   ls -s "$(dirname $(dirname $(realpath $(which web-eid))))/lib/mozilla/native-messaging-hosts/eu.webeid.json" .
   ```

5. Check success

   1. Enable logging: 
   1. Insert Estionan ID card.
   2. Check with DigiDoc that the card reader works and the ID card reader and
      driver works. (Ok)
   3. Goto <https://web-eid.eu/> and click on `[Authenticate]`.

      Type pin1, you should see:
          
          Digital signing
          Welcome, XXX XXX!

       Press the button `[Sign document]`, then type pin2, you should see:
       
            Digital signing
            Welcome, XXX XXX!
            Signature added: example-for-signing.asice

**Comment by getreu** [comment]
# Addendum

The lines 

```sh
mkdir -p ~/.mozilla/native-messaging-hosts/
cd ~/.mozilla/native-messaging-hosts/
ls -s "$(dirname $(dirname $(realpath $(which web-eid))))/lib/mozilla/native-messaging-hosts/eu.webeid.json" .
```

are a workaround until #281710 is fixed.

**Comment by getreu** [comment]
[Jens Getreu's blog - Sign with your Estonian ID card under NixOS](https://blog.getreu.net/20240403-sign-with-estonian-id-card-under-nixos-blog/)
