### ISSUE TITLE
Do a new release

### ISSUE THREAD

**Issue by flokli** [web-eid/web-eid-app#323]
I noticed I'm still running custom git checkout of web-eid app, rather than the last release (2.4.0) due to https://github.com/web-eid/web-eid-app/commit/e8e49162cb2710d22ec107e7098d833a0c11860d.

Is it possible to tag a new release, so this can trickle down in downstream dependencies and reach more users?

**Comment by mrts** [comment]
Yes, we will release 2.5.0 soon.

**Comment by mrts** [comment]
Here we go: https://github.com/web-eid/web-eid-app/releases/tag/v2.5.0
