### ISSUE TITLE
Impossible to login to SEB bank on Ubuntu

### ISSUE THREAD

**Issue by ProximalElk6186** [web-eid/web-eid-app#331]
id-kaardiga sisenemine ebaõnnestus. palun veenduge, et id-kaart on korrektselt lugejas. sulgege kõik brauseri aknad ja proovige seejärel uuesti.
this is the error it gives.
OS: Ubuntu 24.04 LTS
Happens all the time

**Comment by kristelmerilain** [comment]
Thank you for the feedback!
Web eID is not used in SEB for authentication with ID-card because SEB currently uses TLS-CCA solution for ID-card authentication.
Please contact our customer support via [id.ee](https://www.id.ee/en/article/notify-us-of-the-problem/) to resolve your issue.

**Comment by ProximalElk6186** [comment]
OK but why it works in Windows then?

**Comment by kristelmerilain** [comment]
Could you please specify your question?

SEB hasn't integrated the Web eID solution and uses TLS-CCA solution for ID-card authentication. When TLS-CCA solution is used for authentication then user is authenticated in the service through components supported by the operating system or the PKCS#11 driver. You can read more from here - https://www.id.ee/en/article/web-eid/#backward-compatibility

We'll need more information to investigate why TLS-CCA authentication is not working on your Ubuntu 22.04 therefore I recommend to contact our customer support.
