### ISSUE TITLE
No more need browser extension with WebHID / Web Serial ?

### ISSUE THREAD

**Issue by s-kocher** [web-eid/web-eid-app#34]
Hello, I wonder if the recently added browser capabilities such as WebHID or Web Serial (https://developer.chrome.com/blog/new-in-chrome-89/#hardware for some info) allow to avoid having to install a browser extension to be able to interact with devices like smartcards and make the digital signature possible with pure web technologies ?

**Comment by mrts** [comment]
Thanks for the suggestion! These avenues look interesting, but we do not currently have plans to explore them. Initiatives like WebCryptoAPI have failed to deliver (no support for cross-origin keys on hardware tokens is planned), so we are a bit cautious. Please feel free to experiment though and definitely get back with results!

**Comment by s-kocher** [comment]
Ok thanks for feedback, there are interesting feedbacks here : https://stackoverflow.com/search?q=%5Bwebusb%5D+smart+card

Apparently the Web USB API are not designed to handle security topics : 
- [SmartCard reader “Access denied” while claiming interface with Webusb on chrome)](https://stackoverflow.com/questions/46179569/smartcard-reader-access-denied-while-claiming-interface-with-webusb-on-chrome) 
```
Chrome prevents certain interfaces from being accessed for security reasons. These interfaces are the following:

audio
HID
mass storage
smart card
video
audio/video
wireless controller
```
- [Will Chrome support CCID USB device in the future](https://stackoverflow.com/questions/61743035/will-chrome-support-ccid-usb-device-in-the-future) 

It's more [Web Authentication API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API) that is made for security topics but I'm not sure to understand if it can be used for digital signature or is only to authenticate (with device like yubikey)

No many stackoverflow results now for the new WebHID and WebSerial APIs

There is still this document : https://www.w3.org/TR/WebCryptoAPI/#document-signing but hard to find a work in progress for implementation in browser
But smart card are out of scope : https://www.w3.org/TR/WebCryptoAPI/#scope-out-of-scope
```
This API, while allowing applications to generate, retrieve, and manipulate keying material, does not specifically address the provisioning of keys in particular types of key storage, such as secure elements or smart cards
```

May be it will reconsidered someday if more and more countries force their citizen to use hardware devices to sign some administrative operations and some editors like Google want to make that work on their chromebook or a regular browser without additional component like plugin ...

**Comment by mrts** [comment]
Thanks for the research! Yes, maybe this will be reconsidered someday, but until then we have to stick with extensions.
